### ISSUE TITLE
Role Seed

### ISSUE THREAD

**Issue by tpharaoh** [karoys/laravel-native-roles-auth#1]
I am new to the gate stuff, really enjoyed the easy to follow code.

I didn't test it yet, but I am assuming these are backwards, just based on the naming

`
$role_employee              = new \App\Role();
        $role_employee->name        = 'admin';
        $role_employee->description = 'Admin';
        $role_employee->save();
        $role_manager              = new \App\Role();
        $role_manager->name        = 'user';
        $role_manager->description = 'User';
        $role_manager->save();
`

**Comment by karoys** [comment]
thanks for raising issue, now its fixed
